name: Bug Report
description: File a bug report
title: "[Bug]: {replace with description}"
labels: ["a:bug"]
body:
  - type: markdown
    attributes:
      value: |
        1. Ask for help on Discord (https://discord.gg/eP8gE69) #jm-support if you're unsure this is a new issue.
        2. Please search for existing issues before submitting a new one.
        3. Please add the correct MC label to your issue. Example: "[1.12.2] Waypoints are upside down"
        4. Upload your log files or use gist, pastebin, or some similar site. Pasting log contents directly into the issue will get the issue closed immediately.
        5. Completely fill out the template below. Failure to do so is likely to get the issue closed immediately.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: loader
    attributes:
      label: Mod Loader
      description: Select your Mod Loader
      options:
        - Forge
        - NeoForge
        - Fabric
        - Quilt
    validations:
      required: true
  - type: dropdown
    id: mc-version
    attributes:
      label: Minecraft Version
      description: Select your Minecraft version?
      options:
        - 1.20.2
        - 1.20.1
        - 1.20
        - 1.19.4
        - 1.19.3
        - 1.19.2
        - 1.18.2
        - 1.17.x
        - 1.16.5
        - 1.15.x
        - 1.14.x
        - 1.12.2
        - 1.7.10
        - other (please list)
    validations:
      required: true
  - type: dropdown
    id: jm-version
    attributes:
      label: Version
      description: What version of JourneyMap are you running?
      options:
        - 5.9.13
        - 5.9.12
        - 5.9.8
        - 5.9.7
        - 5.9.5
        - 5.9.4
        - 5.9.3
        - 5.8.5
        - 5.7.1
        - other (please list)
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please upload your `.minecraft/journeymap/journeymap.log` and `.minecraft/logs/latest.log` Do not copy and paste into the issue or it will be closed.
